# Generated by Django 6.0.5 on 2026-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_inscription', models.CharField(choices=[('MENTOR', 'Mentor'), ('MENTORE', 'Mentore')], max_length=20)),
                ('statut_inscription', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validee'), ('REFUSEE', 'Refusee')], default='EN_ATTENTE', max_length=20)),
                ('consentement', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
    ]
