# Generated by Django 6.0.5 on 2026-05-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_initial'),
        ('mentorat', '0004_mentorshipassignment_mentoreeprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mentorship_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='mentorat.mentorshipperiod'),
        ),
    ]
