# Generated by Django 6.0.5 on 2026-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_inscription_mentorship_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='completed_session_status',
            field=models.CharField(choices=[('none', 'Non termine'), ('completed', 'Session terminee')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='needs_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscription',
            name='registration_status',
            field=models.CharField(choices=[('registered', 'Inscrit'), ('pending_matching', 'Jumelage requis'), ('matched', 'Jumele'), ('completed', 'Termine')], default='registered', max_length=30),
        ),
        migrations.AddField(
            model_name='inscription',
            name='wants_association_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
