# Generated by Django 6.0.5 on 2026-05-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_evenement', models.DateField()),
                ('heure_evenement', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('type_evenement', models.CharField(choices=[('ATELIER', 'Atelier'), ('CONFERENCE', 'Conference'), ('RESEAUTAGE', 'Reseautage'), ('AUTRE', 'Autre')], default='ATELIER', max_length=30)),
                ('statut_evenement', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('ANNULE', 'Annule'), ('TERMINE', 'Termine')], default='PLANIFIE', max_length=30)),
            ],
            options={
                'ordering': ['date_evenement', 'heure_evenement'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_participation', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('ANNULE', 'Annule')], default='INSCRIT', max_length=30)),
                ('date_reponse', models.DateTimeField(auto_now=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='evenements.evenement')),
            ],
            options={
                'ordering': ['-date_reponse'],
            },
        ),
    ]
