# Generated by Django 6.0.5 on 2026-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/images/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='evenements/videos/'),
        ),
    ]
