# Generated by Django 6.0.5 on 2026-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_partenaire', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/')),
                ('site_web', models.URLField(blank=True)),
                ('type_partenaire', models.CharField(choices=[('ACADEMIQUE', 'Academique'), ('FINANCIER', 'Financier'), ('COMMUNAUTAIRE', 'Communautaire'), ('TECHNOLOGIQUE', 'Technologique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre_affichage', 'nom_partenaire'],
            },
        ),
    ]
