# Generated by Django 6.0.5 on 2026-05-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ordre_niveau', models.PositiveSmallIntegerField(unique=True)),
                ('est_premier_niveau', models.BooleanField(default=False)),
                ('est_dernier_niveau', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordre_niveau'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('ADMIN_PRINCIPAL', 'Administrateur principal'), ('ADMIN_OPERATIONNEL', 'Administrateur operationnel'), ('MENTOR', 'Mentor'), ('MENTORE', 'Mentore')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('langue_preferee', models.CharField(choices=[('FR', 'Francais'), ('EN', 'Anglais')], default='FR', max_length=2)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('disponibilite', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('profil_mentorat', models.CharField(blank=True, choices=[('MENTOR', 'Mentor'), ('MENTORE', 'Mentore'), ('MENTOR_ET_MENTORE', 'Mentor et mentore')], max_length=20, null=True)),
                ('capacite_mentorat', models.PositiveSmallIntegerField(default=0)),
                ('nombre_mentores_actuels', models.PositiveSmallIntegerField(default=0)),
                ('statut_compte', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('REFUSE', 'Refuse'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('niveau_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='users.niveauacademique')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='users.role')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
