# Generated by Django 6.0.5 on 2026-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_default_mentorat_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='domaine_specialite',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_team_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='mini_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_profiles/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='team_display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='wants_to_appear_on_team_page',
            field=models.BooleanField(default=False),
        ),
    ]
