# Generated by Django 6.0.5 on 2026-05-13 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


LEVEL_CODES = {
    1: "mentoree_secondary",
    2: "mentor_level_1",
    3: "mentor_level_2",
    4: "mentor_level_3",
}


def seed_level_codes(apps, schema_editor):
    NiveauAcademique = apps.get_model("users", "NiveauAcademique")
    for ordre_niveau, code in LEVEL_CODES.items():
        NiveauAcademique.objects.filter(ordre_niveau=ordre_niveau).update(code=code)


def clear_level_codes(apps, schema_editor):
    NiveauAcademique = apps.get_model("users", "NiveauAcademique")
    NiveauAcademique.objects.filter(code__in=LEVEL_CODES.values()).update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_academic_level_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveauacademique',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(seed_level_codes, clear_level_codes),
        migrations.CreateModel(
            name='LoginVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge_id', 'used_at', 'expires_at'], name='users_login_challen_578b0b_idx'), models.Index(fields=['user', 'created_at'], name='users_login_user_id_492860_idx')],
            },
        ),
    ]
