# Generated by Django 6.0.5 on 2026-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_niveauacademique_code_loginverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='can_appear_on_about_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='public_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
    ]
