# Generated by Django 6.0.5 on 2026-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_utilisateur_can_appear_on_about_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='public_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
