# Generated by Django 6.0.5 on 2026-05-14 20:03

from django.db import migrations, models


def replace_refused_account_status(apps, schema_editor):
    utilisateur = apps.get_model("users", "Utilisateur")
    utilisateur.objects.filter(statut_compte="REFUSE").update(statut_compte="INACTIF")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_utilisateur_public_title'),
    ]

    operations = [
        migrations.RunPython(
            replace_refused_account_status,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_compte',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=20),
        ),
    ]
