# Generated by Django 6.0.5 on 2026-05-14 22:21

from django.db import migrations, models
from django.utils import timezone


def seed_existing_public_admin_profiles(apps, schema_editor):
    Utilisateur = apps.get_model("users", "Utilisateur")
    for user in Utilisateur.objects.filter(can_appear_on_about_page=True).exclude(public_title=""):
        user.approved_public_prenom = user.prenom
        user.approved_public_nom = user.nom
        user.approved_public_title = user.public_title
        user.approved_public_description = user.public_description
        user.approved_public_photo = user.public_photo
        user.is_public_profile_approved = True
        user.pending_public_validation = False
        user.public_profile_status = "VALIDE"
        user.public_profile_updated_at = timezone.now()
        user.save(
            update_fields=[
                "approved_public_prenom",
                "approved_public_nom",
                "approved_public_title",
                "approved_public_description",
                "approved_public_photo",
                "is_public_profile_approved",
                "pending_public_validation",
                "public_profile_status",
                "public_profile_updated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_utilisateur_statut_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='approved_public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='approved_public_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='approved_public_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/approved/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='approved_public_prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='approved_public_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_public_profile_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pending_public_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='public_profile_status',
            field=models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REFUSE', 'Refuse')], default='NON_SOUMIS', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='public_profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(seed_existing_public_admin_profiles, migrations.RunPython.noop),
    ]
