# Generated by Django 6.0.5 on 2026-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutomatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(choices=[('INSCRIPTION_RECUE', 'Inscription recue'), ('INSCRIPTION_VALIDEE', 'Inscription validee'), ('INSCRIPTION_REFUSEE', 'Inscription refusee'), ('JUMELAGE', 'Jumelage'), ('RAPPEL_EVENEMENT', 'Rappel evenement')], max_length=50)),
                ('sujet_fr', models.CharField(max_length=255)),
                ('sujet_en', models.CharField(blank=True, max_length=255)),
                ('contenu_fr', models.TextField()),
                ('contenu_en', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut_envoi', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoye'), ('ECHEC', 'Echec')], default='EN_ATTENTE', max_length=20)),
            ],
            options={
                'ordering': ['-date_envoi', '-id'],
            },
        ),
    ]
