# Generated by Django 6.0.5 on 2026-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jumelage', models.DateTimeField(auto_now_add=True)),
                ('statut_jumelage', models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Termine'), ('ANNULE', 'Annule'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
            ],
            options={
                'ordering': ['-date_jumelage'],
            },
        ),
    ]
