# Generated by Django 6.0.5 on 2026-05-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorat',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorats_comme_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorat',
            name='mentore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorats_comme_mentore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mentorat',
            constraint=models.UniqueConstraint(condition=models.Q(('statut_jumelage', 'ACTIF')), fields=('mentore',), name='unique_mentorat_actif_par_mentore'),
        ),
    ]
