# Generated by Django 6.0.5 on 2026-05-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_mentores', models.PositiveSmallIntegerField(default=5)),
                ('max_sessions_per_week', models.PositiveSmallIntegerField(default=3)),
                ('default_session_duration', models.PositiveSmallIntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (90, '90 minutes')], default=60)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mentor__nom', 'mentor__prenom'],
            },
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mentor__nom', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['mentor', 'weekday', 'is_active'], name='mentorat_me_mentor__479b66_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorAvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-end_date'],
                'indexes': [models.Index(fields=['mentor', 'start_date', 'end_date'], name='mentorat_me_mentor__38901e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmee'), ('cancelled', 'Annulee'), ('completed', 'Terminee')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings_as_mentore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['mentor', 'starts_at', 'ends_at', 'status'], name='mentorat_se_mentor__52c77f_idx'), models.Index(fields=['mentore', 'starts_at'], name='mentorat_se_mentore_d34c55_idx')],
            },
        ),
    ]
