# Generated by Django 6.0.5 on 2026-05-10 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0003_mentorprofile_mentoravailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminee'), ('suspended', 'Suspendue')], default='active', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_assignments_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_assignments_as_mentoree', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MentoreeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Moyen'), ('watch', 'A surveiller'), ('difficulty', 'En difficulte')], default='average', max_length=20)),
                ('progress_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulties', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('mentor_opinion', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='mentorat.mentorshipassignment')),
            ],
            options={
                'ordering': ['assignment__mentoree__nom', 'assignment__mentoree__prenom'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('required_sessions', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('completed', 'Terminee'), ('archived', 'Archivee')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
                'indexes': [models.Index(fields=['status', 'start_date', 'end_date'], name='mentorat_me_status_6370f6_idx')],
            },
        ),
        migrations.AddField(
            model_name='mentorshipassignment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='mentorat.mentorshipperiod'),
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField()),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmee'), ('completed', 'Realisee'), ('cancelled', 'Annulee'), ('postponed', 'Reportee'), ('absent', 'Absente')], default='scheduled', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('mentor_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorat.mentorshipassignment')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time', 'session_number'],
            },
        ),
        migrations.AddIndex(
            model_name='mentorshipassignment',
            index=models.Index(fields=['mentor', 'period', 'status'], name='mentorat_me_mentor__e36850_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipassignment',
            index=models.Index(fields=['mentoree', 'period', 'status'], name='mentorat_me_mentore_c3b0cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorshipassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('mentoree', 'period'), name='unique_active_assignment_per_mentoree_period'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['assignment', 'status'], name='mentorat_me_assignm_03ccbe_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['scheduled_date', 'status'], name='mentorat_me_schedul_669349_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorshipsession',
            constraint=models.UniqueConstraint(fields=('assignment', 'session_number'), name='unique_session_number_per_assignment'),
        ),
    ]
