# Generated by Django 6.0.5 on 2026-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0004_mentorshipassignment_mentoreeprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipperiod',
            name='auto_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
